### ISSUE TITLE
ARouter + Hilt >= 2.46 build failure

### ISSUE THREAD

**Issue by blundell** [JailedBird/ArouterGradlePlugin#11]
I am not sure if this is a problem with the ArouterGradlePlugin or a problem with Arouter itself.
So I apologise if I am asking in the wrong place :-)

I have made a reproduction repo that shows the problem:

https://github.com/blundell/ARouterHiltIssue/tree/main

```
:app:hiltJavaCompileDebug FAILED	
error: ARouter::Compiler An exception is encountered, [These no module name, at 'build.gradle', like :	
  android {	
      defaultConfig {	
          ...	
          javaCompileOptions {	
              annotationProcessorOptions {	
                  arguments = [AROUTER_MODULE_NAME: project.getName()]	
              }	
          }	
      }	
  }	
  ]	
1 error
```

This happens when `com.google.dagger.hilt.android` gradle plugin version is >= `2.46`.

But the build will build successfully if hilt plugin is <= `2.45`.

Any ideas please🙏

**Comment by JailedBird** [comment]
1: The issue occur in arouter-compiler 
Your arouter-compiler is : arouter-compiler = { module = "com.github.jadepeakpoet.ARouter:arouter-compiler", version.ref = "arouter" }
the jadepeakpoet's Arouter repo is https://github.com/jadepeakpoet/ARouter 
2: in jadepeakpoet/ARouter compiler, thie problem occur in here, check your AROUTER_MODULE_NAME config

![image](https://github.com/JailedBird/ArouterGradlePlugin/assets/113177053/9e45ff3c-0d60-4c53-bbcf-f44f33449815)

**Comment by blundell** [comment]
It seems even with correct config (and correct AROUTER_MODULE_NAME) certain setup's fail to find the annotation processor arguments. (Also raised here: https://github.com/alibaba/ARouter/issues/1051)

**Comment by JailedBird** [comment]
Can i close this issue?

**Comment by blundell** [comment]
yeah no problem, thanks!

**Comment by Bert-King** [comment]
如果hilt版本>= 2.46，则可以考虑在build.gradle添加这个试一下
`
android {
     ...
     
     hilt {
       enableExperimentalClasspathAggregation = true
        enableAggregatingTask = false
    }
    
     ...
 }
`
