### ISSUE TITLE
feat-agp8的分支现在可以用了吗？

### ISSUE THREAD

**Issue by danatechgithub4** [JailedBird/ArouterGradlePlugin#3]
![image](https://github.com/JailedBird/ArouterGradlePlugin/assets/127659297/bd202028-6c66-4003-8a83-93567e5fa648)
我不需要关系性能问题，因为只有在CI自动化打包的时候我才会启用[ArouterGradlePlugin](https://github.com/JailedBird/ArouterGradlePlugin)
https://github.com/JailedBird/ArouterGradlePlugin/tree/feat-agp8

非常感谢作者对[ARouter](https://github.com/alibaba/ARouter)升级维护

**Comment by danatechgithub4** [comment]
其实可以直接用main分支的，反正也支持AGP8对吧。

**Comment by JailedBird** [comment]
直接用main就行了；但是你们用于生产的话，最好自测下哈；
