### ISSUE TITLE
Debug的时候也会插桩，编译慢了不少

### ISSUE THREAD

**Issue by xiaojianli** [JailedBird/ArouterGradlePlugin#7]
RT

**Comment by JailedBird** [comment]
遍历所有class然后进行transform确实很慢，有种方式你可以试试：
改一下插件代码，debug阶段关闭transform，这时候会使用Arouter 便利dex获取生成的路由类（首次运行慢一点，第二次会保存在SP里面，调试阶段应该还是有用的）；

**Comment by JailedBird** [comment]
我晚点加一个debug的transform启用配置；

**Comment by JailedBird** [comment]
麻烦更新到1.0.2-beta01这个版本试试， 
在app模块添加 可以避免debug阶段transform；
```
arouter_config {
    disableTransformWhenDebugBuild = true
}
```

**Comment by xiaojianli** [comment]
#6 和 这个issue 都验证了，没有问题，能否发个正式版

**Comment by JailedBird** [comment]
ok，晚点弄

**Comment by xiaojianli** [comment]
> ok，晚点弄
:+1:

**Comment by JailedBird** [comment]
> #6 和 这个issue 都验证了，没有问题，能否发个正式版

已发布1.0.2，可以去看下README

**Comment by midiao** [comment]
你好，如果开启增量编译是不是也可以修改debug慢的问题？

**Comment by JailedBird** [comment]
> 你好，如果开启增量编译是不是也可以修改debug慢的问题？

AGP8的transform的增量机制我也不是很了解，建议开启先试试；优化效果不好再试试参数关闭debug的transform
