### ISSUE TITLE
运行报错 NoClassDefFoundError: Failed resolution of: Lcom/alibaba/android/arouter/routes/ARouter

### ISSUE THREAD

**Issue by NEIL-ORZ** [JailedBird/ArouterGradlePlugin#8]
` 
 dependencies {
    classpath "io.github.JailedBird:arouter-gradle-plugin:1.0.1"
  }
}

apply plugin: "io.github.JailedBird.ARouterPlugin"
`
使用以上代码，从 agp 4.2 升级到 agp 7.4.2 时运行正常，再升级到 agp 8.2.2 时运行初始化过程中报错，求解一下，麻烦了
![image](https://github.com/JailedBird/ArouterGradlePlugin/assets/66617546/dac00be4-790b-4461-92e8-9743224deb4d).
![1711966840(1)](https://github.com/JailedBird/ArouterGradlePlugin/assets/66617546/7190a2ec-5252-4108-847e-cbedca82c9ec)

**Comment by JailedBird** [comment]
build目录下找到对应产物apk，打开看下dex里面这个插装类是否存在；
![image](https://github.com/JailedBird/ArouterGradlePlugin/assets/113177053/e3b6fdf6-214b-46f5-8ff1-603ae6db4e7f)

**Comment by JailedBird** [comment]
你的问题，类似于demo中的 ARouter$$Root$$app中报错找不到ARouter$$Group$$app，如下图：

![image](https://github.com/JailedBird/ArouterGradlePlugin/assets/113177053/e56fad0c-549c-483b-b613-1c939eeaa489)

但是这在Java to Class阶段是不可能出现的，因为这样会造成编译中断；
另外，这个直接使用Class类型，所以应该和混淆、R8之类的也没啥关系； 
我猜的唯一原因是 插桩的时候导致这个漏掉了？ 但是demo中使用AGP8.2.2中没复现出来； 

希望得到你的回复，不然我三天后就关闭了哈；

测试分支：https://github.com/JailedBird/ArouterGradlePlugin/commit/eda27eee1e703d2bef8c2298412ecd3ae8addec6#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06

**Comment by JailedBird** [comment]
没得回复，我关闭了哈； 有问题请继续反馈；

**Comment by NEIL-ORZ** [comment]
1.0.2-beta01 已解决
